services:
  postgres:
    image: postgres:16
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - weather_pg_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

volumes:
  weather_pg_data:
